            - name: Run Py Script
  # You may pin to the exact commit or the version.
  # uses: revanth-reddy/runpy-action@bd650eac0e5e38c42fae951932db067e9c91d6e9
  uses: revanth-reddy/runpy-action@release
  with:
    # Py script
    script: 
    # Fail step if the return code from running the script is non-zero
    fail-on-error: # optional, default is true
    # Include utility functions
    util: # optional, default is true
          

from flask import Flask, render_template, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Configure the database URI for SQLAlchemy (SQLite in this example)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///example.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Initialize SQLAlchemy
db = SQLAlchemy(app)

# Define a model for the database table
class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    message = db.Column(db.Text, nullable=False)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        # Retrieve form data
        name = request.form['name']
        email = request.form['email']
        message = request.form['message']
        
        # Create a new Contact object
        new_contact = Contact(name=name, email=email, message=message)
        
        # Add the new contact to the database
        db.session.add(new_contact)
        db.session.commit()
        
        # Redirect to a thank you page
        return redirect(url_for('thank_you'))

    return render_template('index.html')

@app.route('/thank-you')
def thank_you():
    return render_template('thank_you.html')

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)
